### ISSUE TITLE
Lua-posix is missing on redhat8-deps

### ISSUE THREAD

**Issue by sandermitre** [idiv-biodiversity/ansible-role-lmod#12]
When running the role I got the following error with LMOD 8.7.7

"Error: The follow lua module(s) are missing:  posix", "", "You can not run Lmod without:  posix"

I installed the lua-posix package and all is good, so it just needs to be added to the deps file. I can make a pull request if that helps.

**Comment by wookietreiber** [comment]
Fixed by 39a764d48f55bc908e9b46ecc90ee474ba0131b4 and released in v2.4.4.
